FROM ubuntu:12.04

RUN echo 'deb http://de.archive.ubuntu.com/ubuntu/ precise main restricted universe multiverse' > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install --yes --no-install-recommends mysql-client

